Add gplazma2-jython module for auth using Python
dCache/dcache pull request #7627
Opened 2024-07-26 14:11 UTC by ThePhisch

Adds a new gplazma2 module to the project which uses Jython to parse and execute Python files (only version 2.7 supported) within the dcache Java runtime. This enables site admins to quickly script authentication plugins without needing to understand or write the native dcache Java code.

This commit includes a sample "sample_plugin.py" auth plugin which is used during testing and serves as a reference.

### Implementation Details

Jython limits the Python version to version 2.7. The Python files are currently stored directly within the source
folder, i.e.
`modules/gplazma2-pyscript/gplazma2-pyscript/sample_plugin.py`. Multiple files can be inserted which will be executed
sequentially but in no particular order.

Each Python file shall be structured to contain one function `py_auth(public_credentials, private_credentials,
principals)` which returns a boolean whether the authentication was successful. Returning `False` will trigger an
`AuthenticationException` in Java. Each parameter passed to `py_auth` will be a Python set.

- `private_credentials` is a set of strings, integers or floats (implemented in Java as `String || Number`
- `public_credentials` is the same as `private_credentials`
- `principals` will be a set of strings in the form `<principal_type>:<value>`, i.e. a pair of strings separated by a
  colon. Consider `org.dcache.auth.Subjects#principalsFromArgs` to see how the principal type string maps to the
  principals classes.

The conversion from a set of principals to a set of strings is done entirely within the `authenticate` method of the
`PyscriptPlugin`-class. The Python file only ever sees a set of strings, while someone using the plugin will only ever
need to pass a set of principals from within Java. The conversion is done using existing functions.

### Tests

A test class `PyscriptPluginTest` has been added that makes use of the internal logic of the sample `sample_plugin.py`. The logic is simple and is repeated in the Java class and the Python file as a comment.

Signed-off-by: Anton Schwarz anton.schwarz@desy.de

2024-07-29 09:58 UTC, kofemann commented
ok to test

2024-07-29 10:00 UTC, kofemann commented on modules/gplazma2-jython/pom.xml
> +    <version>10.1.0-SNAPSHOT</version>
The master is already `10.2.0-SNAPSHOT`

2024-07-29 10:06 UTC, kofemann commented on modules/gplazma2-jython/src/main/java/org/dcache/gplazma/jython/JythonPlugin.java
> +        if (Files.isDirectory(path)) {
`List<Path> elements = Files.list(Path.of(directoryPath)).toList();`

2024-07-29 10:08 UTC, kofemann commented on modules/gplazma2-jython/src/main/java/org/dcache/gplazma/jython/JythonPlugin.java
> +                LOGGER.debug("gplazma2-jython running " + pluginPath.toString());
Please use placeholders, like:

```
LOGGER.debug("gplazma2-jython running {}", pluginPath);
```

2024-07-29 10:10 UTC, kofemann commented on modules/gplazma2-jython/src/main/java/org/dcache/gplazma/jython/JythonPlugin.java
> +                        Paths.get(pluginPath.toString())
`pluginPath` is already `Path`. Can't we use it directly: `Files.lines(pluginPath)`?

2024-07-29 10:11 UTC, kofemann commented on modules/gplazma2-jython/src/main/java/org/dcache/gplazma/jython/JythonPlugin.java
> +                            "GPlazma2-Jython: Public Credential "
The same here, please use placeholders. That way, string concatenation will run only when debug logging is enabled.

2024-07-29 10:17 UTC, kofemann commented on modules/gplazma2-jython/src/main/java/org/dcache/gplazma/jython/JythonPlugin.java
> +                List<String> convertedPyPrincipals = pyPrincipals.stream().toList();
I think `List.copyOf(pyPrincipals)` is a better option.

2024-07-29 10:20 UTC, kofemann commented on modules/gplazma2-jython/src/main/resources/META-INF/gplazma-plugins.xml
> +    <name>Jython</name>
Please make plugin name lowercase to match other plugins. Maybe `pyscript` (or similar) is a better name.  `Jython` tells too little to dCache admins.

2024-07-29 10:20 UTC, kofemann requested changes
Thanks for the nice work!

2024-08-02 07:41 UTC, ThePhisch commented
Completed requested changes, will add documentation and configuration in two separate PRs.

2024-08-06 08:43 UTC, kofemann approved these changes
Very nice, thanks!
One little cosmetic change. May be the wou move `gplazma2-pyscript/sample_plugin.py` into `src/main/demo` directory

2024-08-09 13:38 UTC, merged